//
// Created by Laurent Giustignano on 25/11/2021.
//

#ifndef MQTTCHANTIER_CONFIG_H
#define MQTTCHANTIER_CONFIG_H

// COMPLETER LES DEFINE VIDE

#define SSID
#define SSID_PWD
#define IP_MQTT_SERVER
#define PORT_MQTT_SERVER
#define TOPIC_TEMPERATURE_MESURE
#define TOPIC_TEMPERATURE_MOYENNE
#define TOPIC_PORTE_ETAT

// NE PAS MODIFIER
#define DHTTYPE DHT11
#define DHTPIN GPIO_NUM_4
#define PORTE_PIN GPIO_NUM_26

#endif //MQTTCHANTIER_CONFIG_H
